FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN rm -rf src public node_modules

RUN npm install -g serve

EXPOSE 3000

CMD [ "serve", "-s", "build" ]